DROP TABLE IF EXISTS `CAR`;

CREATE TABLE `CAR` (
  `REGISTRATION_NUMBER` char(7) NOT NULL,
  `MODEL_NAME` varchar(25) NOT NULL,
  `MAKE` varchar(25) NOT NULL,
  `MODEL_YEAR` int(4) NOT NULL,
  `MILEAGE` int(11) NOT NULL,
  `CAR_CATEGORY_NAME` varchar(25) NOT NULL,
  `LOC_ID` char(4) NOT NULL,
  `AVAILABILITY_FLAG` char(1) NOT NULL,
  PRIMARY KEY (`REGISTRATION_NUMBER`),
  KEY `CARFK1` (`CAR_CATEGORY_NAME`),
  KEY `CARFK2` (`LOC_ID`),
  CONSTRAINT `CARFK1` FOREIGN KEY (`CAR_CATEGORY_NAME`) REFERENCES `CAR_CATEGORY` (`CATEGORY_NAME`),
  CONSTRAINT `CARFK2` FOREIGN KEY (`LOC_ID`) REFERENCES `LOCATION_DETAILS` (`LOCATION_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
